### ISSUE TITLE
Error: Cannot find module 'request'

### ISSUE THREAD

**Issue by ianchanning** [draconar/grab_packt#1]
You need to run `npm install` in the directory before running `node server.js` otherwise you get the following error (on Windows):

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\inetpub\wwwroot\grab_packt\server.js:1:77)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

**Comment by philiptruax** [comment]
Thanks this helped me on linux too.

**Comment by draconar** [comment]
you are right. I forgot to add it to the instructions. Thank you.
